<?xml version="1.0"?>
<package format="3">
  <name>coramo_brain</name>
  <version>0.1.0</version>
  <description>Cerebro de CORAMO: voz a accion.</description>
  <maintainer email="felipe1024@gmail.com">Felipe Ballesteros</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>coramo_msgs</depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
